export interface IDataGasto {
	appPresupuestaria?: string;
	CodAre?: number;
	CodArt?: number;
	CodCap: string;
	CodCon?: number;
	CodEco: string;
	CodGru?: number;
	CodOrg: string;
	CodPol?: number;
	CodPro: string;
	Definitivas: string;
	DesAre?: string;
	DesArt?: string;
	DesCap: string;
	DesCon?: string;
	DesEco: string;
	DesGru?: string;
	DesOrg: string;
	DesPol?: string;
	DesPro: string;
	GastosComprometidos: string;
	Iniciales: string;
	Modificaciones: string;
	ObligacionesPendientePago: string;
	ObligacionesReconocidasNetas: string;
	Pagos: string;
	RemanenteCredito: string;
}
