export interface IDataGasto {
	appPresupuestaria?: string;
	CodAre?: number;
	CodArt?: number;
	CodCap: string;
	CodCon?: number;
	CodEco: string;
	CodGru?: number;
	CodOrg: string;
	CodPol?: number;
	CodPro: string;
	Definitivas1: string;
	DesAre?: string;
	DesArt?: string;
	DesCap: string;
	DesCon?: string;
	DesEco: string;
	DesGru?: string;
	DesOrg: string;
	DesPol?: string;
	DesPro: string;
	GastosComprometidos1: string;
	Iniciales1: string;
	Modificaciones1: string;
	ObligacionesPendientePago1: string;
	ObligacionesReconocidasNetas1: string;
	Pagos1: string;
	RemanenteCredito1: string;
}
